// SPDX-License-Identifier: MIT
#pragma once
static const char ABOUTPAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Haier · О системе</title>__STYLE__</head><body data-page="about">__NAV__<main><h1>О системе</h1><p class="muted">Версия, соединения и запас памяти контроллера</p><p id="message" role="status">Чтение данных…</p><section class="card"><dl id="info"></dl></section><details style="margin-top:16px"><summary>Диагностика</summary><pre id="raw"></pre><p><a href="/diagnostics/recovery" target="_blank" rel="noopener">Отчёт последнего сбоя / Last recovery report (JSON)</a></p></details><section class="card" style="margin-top:16px"><h2>Перезагрузка платы / Restart controller</h2><p>Перезапускает только ESP32. Настройки сохраняются. Связь через UART-мост и веб-интерфейс временно прервётся. Не выполняйте во время обновления штатного модуля Haier.</p><button id="restart" type="button">Перезагрузить плату / Restart</button><p id="restart-result" role="status"></p></section><section class="card" style="margin-top:16px"><h2>О проекте</h2><p>Независимое расширение возможностей кондиционера Haier. Локальное управление и подключение к Home Assistant через MQTT.</p><p>Используются ESPHome, HaierProtocol и ESP-MQTT. Лицензии сторонних компонентов сохранены в исходном проекте. Это не официальное ПО Haier.</p></section></main><footer>Локальный контроллер Haier · ESP32-S3</footer><script>const el=id=>document.getElementById(id);async function refresh(){try{if(document.hidden)return;let r=await fetch('/health',{cache:'no-store'});if(!r.ok)throw Error();let s=await r.json(),kb=n=>(n/1024).toFixed(1)+' КБ';let rows=[['Прошивка',s.version],['Автовосстановление связи',s.recovery_state],['Контроллер','ESP32-S3 · N16R8'],['PSRAM',kb(s.psram_size)+' / свободно '+kb(s.free_psram)],['Flash',(s.flash_size/1048576).toFixed(0)+' МБ'],['Адрес',s.ip],['Время работы',Math.floor(s.uptime_s/3600)+' ч '+Math.floor(s.uptime_s%3600/60)+' мин'],['Свободная RAM',kb(s.free_heap)],['Минимум RAM за сеанс',kb(s.min_heap)],['Крупнейший свободный блок',kb(s.max_block)],['Оценка раздробленности heap',s.fragmentation+' %'],['Wi-Fi',s.wifi?'Подключён':'Нет связи'],['OTA',s.ota?'Доступно':'Недоступно'],['Сохранение настроек',s.storage_ok?'Исправно':'Ошибка']];el('info').replaceChildren();for(let [k,v] of rows){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;el('info').append(dt,dd)}el('raw').textContent=JSON.stringify(s,null,2);el('message').textContent='Данные обновлены'}catch(e){el('message').textContent='Не удалось обновить данные'}finally{setTimeout(refresh,10000)}}refresh();el('restart').onclick=async()=>{
if(!confirm('Перезагрузить плату ESP32? Связь временно прервётся. / Restart the ESP32 controller?'))return;
const button=el('restart'),message=el('restart-result');button.disabled=true;
try{const r=await fetch('/system/restart',{method:'POST',body:new URLSearchParams({token:'__TOKEN__',confirm:'restart'})});
if(!r.ok)throw Error(await r.text());
message.textContent='Перезагрузка принята. Через несколько секунд обновите страницу. / Restart accepted. Reload this page shortly.';
}catch(e){message.textContent='Не удалось подтвердить перезагрузку: '+e.message;button.disabled=false;}
};</script></body></html>)HTML";
